### ISSUE TITLE
"Native Client is installed!" when stderr output too large?

### ISSUE THREAD

**Issue by LazyBumHorse** [andy-portmen/external-application-button#7]
I'm on Firefox and use this addon to open videos in mpv, which works great, but I sometimes still get the "Native Client is installed!" message after mpv closes.
After finding the debug switch for Firefox (-jsconsole) and way too many tries I was finally able to get the error message:

> Native application tried to send a message of 3729037 bytes, which exceeds the limit of 1048576 bytes.  NativeMessaging.jsm:167
Unchecked lastError value: Error: Native application tried to send a message of 3729037 bytes, which exceeds the limit of 1048576 bytes.  ExtensionCommon.jsm:407
stderr output from native app com.add0n.node: events.js:160
stderr output from native app com.add0n.node:       throw er; // Unhandled 'error' event
stderr output from native app com.add0n.node:       ^
stderr output from native app com.add0n.node: 
stderr output from native app com.add0n.node: Error: no writecb in Transform class
stderr output from native app com.add0n.node:     at afterTransform (_stream_transform.js:71:33)
stderr output from native app com.add0n.node:     at TransformState.afterTransform (_stream_transform.js:54:12)
stderr output from native app com.add0n.node:     at Transform.observe (...\AppData\Local\com.add0n.node\host.js:474:5)
stderr output from native app com.add0n.node:     at Transform._transform (...\AppData\Local\com.add0n.node\messaging.js:107:10)
stderr output from native app com.add0n.node:     at Transform._read (_stream_transform.js:167:10)
stderr output from native app com.add0n.node:     at Transform._write (_stream_transform.js:155:12)
stderr output from native app com.add0n.node:     at doWrite (_stream_writable.js:331:12)
stderr output from native app com.add0n.node:     at writeOrBuffer (_stream_writable.js:317:5)
stderr output from native app com.add0n.node:     at Transform.Writable.write (_stream_writable.js:243:11)
stderr output from native app com.add0n.node:     at Input.ondata (_stream_readable.js:555:20)

Not quiet sure if the problem is the message size exceeding 1MB or if it's about that "no writecb in Transform class" error. The latter is [apparently](https://github.com/ipfs/js-ipfs/issues/318#issuecomment-225293878) caused by multiple Transform callbacks.

The former might have something to do with the fact that mpv writes lots of status messages in the form of
> AV: 00:00:00 / 00:15:23 (0%) A-V:  0.000 Dropped: 1 Cache:  1s+0KB

to stderr, which probably get collected into the NativeMessaging message and exceed the 1MB limit. This would also explain why I mostly get the "Native Client is installed!" message when the video I was watching would be running for a longer time.

As a workaround it might be enough to use the --quiet (or --really-quiet or --no-terminal) switch for mpv which prevents these messages, which I'm gonna try now.

**Comment by LazyBumHorse** [comment]
Just a heads-up: I didn't get a single "Native Client is installed!" message after using mpv's --no-terminal switch. This might still be an issue for other programs.
